##
## SPDX-License-Identifier: Apache-2.0
##
##
version: 2.1
orbs:
  go: circleci/go@0.2.0
  splunk-app-package:
    jobs:
      package:
        docker:
          - image: livehybrid/splunk-ci-build:latest
        steps:
          - checkout
          - run:
              name: Setup Environment
              command: |
                echo "Nothing to do here, all done inside splunk-ci-build image"
                rm -rf build/
          - run:
              name: Generate Documentation
              command: |
                cat README.md | sed 's/package\/appserver/appserver/g' > package/README.md
                grip README.md --export README.html --title ""
                pandoc -s README.html -o package/README.pdf
          - run:
              name: Generate Addon
              command: |
                source ~/.venv/bin/activate
                if [[ ! -z "${CIRCLE_TAG}" ]]
                then
                VERSION=${CIRCLE_TAG}
                ucc-gen
                else
                VERSION="0.0.0${CIRCLE_BRANCH//\//_}"
                ucc-gen --ta-version=$VERSION
                fi
                echo "-------------------------"
                echo "Building Version $VERSION"
                echo "-------------------------"
          - run:
              name: Generating package
              command: |
                PACKAGE_ID=$(ls output/)
                BUILD_DIR=output/$PACKAGE_ID              
                source ~/.venv/bin/activate                
                slim generate-manifest $BUILD_DIR --update >/tmp/app.manifest   || true
                cp  /tmp/app.manifest  $BUILD_DIR/app.manifest
                mkdir -p build/package/splunkbase
                mkdir -p build/package/deployment
                slim package -o build/package/splunkbase $BUILD_DIR 
                mkdir -p build/package/deployment
                PACKAGE=$(ls build/package/splunkbase/*)
                slim partition $PACKAGE -o build/package/deployment/ || true
                slim validate $PACKAGE
          - persist_to_workspace:
              root: /home/circleci/project
              paths:
                - output
                - build
          - store_artifacts:
              path: build/package/splunkbase
              destination: build-package-splunkbase
          - store_artifacts:
              path: build/package/deployment
              destination: build-package-deployment
          - store_artifacts:
              path: build/VERSION
              destination: build-version
      publish-gh:
        docker:
          - image: cimg/go:1.13
        steps:
          - attach_workspace:
              at: /tmp/workspace
          - checkout
          - run:
              name: "Publish on GitHub"
              command: |
                PATH=$PATH:/usr/local/go/bin
                go get -v -u github.com/tcnksm/ghr
                [[ "${CIRCLE_TAG}" =~ ^v[0-9]*.[0-9]*.[0-9]*$ ]] || export ISPRE=-prerelease
                $HOME/go/bin/ghr -t ${GH_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} ${ISPRE} -delete "${CIRCLE_TAG}" /tmp/workspace/build/package/splunkbase
                $HOME/go/bin/ghr -t ${GH_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} ${ISPRE} "${CIRCLE_TAG}" /tmp/workspace/build/package/deployment

workflows:
  build:
    jobs:
      - splunk-app-package/package:
          name: package
          filters:
            branches:
              only: /.*/
            tags:
              only: /^v\d*\.\d*\.\d*.*$/
      - splunk-app-package/publish-gh:
          context:
            - gdi-github
          requires:
            - package
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d*\.\d*\.\d*.*$/